:baseUrl = http://localhost:3000
:token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InR0dE1CNHN5RjZXWnlWbGoiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTcyODkxNTM3LCJleHAiOjE1NzI4OTUxMzd9.Gd2pr4xuWvZLZTRv3bC7JnFrsOZz-L4WJFkXrb9YFOw

# Authenticate
POST :baseUrl/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "thisShouldBeHashed"
}

# Verify
GET :baseUrl/verify
Authentication: :token